stages:
- lint
- build

image: node:slim

lint:
        stage: lint
        tags:
        - shared
        script:
        - npm install
        - npm install npm-run-all
        - npm install eslint
        - npm install lockfile-lint
        - npm run lint

buid:
        stage: build
        tags:
        - shared
        script:
        - npm install
        - npm run css-compile
        artifacts:
                paths:
                - dist/*
