stages:
- build

images: node:slim

buid:
        stage: build
        tags:
        - shared
        script:
        - npm install
        - npm run css-compile
        artifacts:
                paths:
                - dist/*
