stages:
  - lint
  - build

image: node:17.4.0

lint:
  stage: lint
  tags:
    - shared
  before_script:
    - npm install
  script:
    - npm run lint

build:
  stage: build
  only:
    refs:
      - main
      - merge_requests # to test
  tags:
    - shared
  before_script:
    - npm install
  script:
    - npm run css-compile
    - cp assets/* dist -r
  artifacts:
    paths:
      - dist/*
